title:             HeatLai's Blog
email:             hitgunlai@gmail.com
description:       聽說寫部落格考試會得一百分
author:            HeatLai
baseurl:           "/"
#url:               "https://heat.hypenode.tw"
keywords:          ["blog", "heat", "lai", "HeatLai"]

# Social Profiles
#twitter_username:  SBootstrap
github_username:   heatlai
#facebook_username: StartBootstrap

# Build settings
timezone:          Asia/Taipei
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate