title:             Heat's Blog
email:             hitgunlai@gmail.com
description:       聽說寫部落格考試會得一百分
author:            Heat Lai
baseurl:           "/"
permalink:         "/post/:year/:month/:day/:title"
url:               "https://heat.hypenode.tw"
keywords:          ["blog", "heat", "lai"]

# Social Profiles
#twitter_username:  SBootstrap
github_username:   heatlai
#facebook_username: StartBootstrap

# Disqus Comments
disqus:
  shortname: heatlai

# Build settings
timezone:          Asia/Taipei
markdown:          kramdown
#paginate:          5
#paginate_path:     "/posts/page:num/"
plugins:
  #- jekyll-feed
  #- jekyll-paginate