title:             HeatLai's Blog
email:             hitgunlai@gmail.com
description:       聽說寫部落格考試會得一百分
author:            HeatLai
baseurl:           ""
permalink:         "/post/:year/:month/:day/:title/"
url:               "https://heat.hypenode.tw"
keywords:          ["blog", "heatlai"]

ad_enable: true

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   heatlai
#facebook_username: StartBootstrap
linkedin_username: heatlai

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Disqus Comments
disqus:
  shortname: heatlai

# Build settings
timezone:          Asia/Taipei
markdown:          kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-github-metadata