title:             Heat's Blog
email:             hitgunlai@gmail.com
description:       聽說寫部落格考試會得一百分
author:            Heat Lai
baseurl:           "/"
#url:               "https://heat.hypenode.tw"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   heatlai
#facebook_username: StartBootstrap

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags: [tags,to,ignore]

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
